#!/usr/bin/env python3
"""Emit one manifest.json component entry with real git blob SHAs.

manifest.json's own $schema_note says every entry is "generated by a throwaway
dev-time script against the source repo's real git blob SHAs (git rev-parse
HEAD:<path>) - never hand-transcribed." No such script survived in this repo,
so component entries after the first six were at risk of being typed in by
hand. This is that script, kept for real this time.

Usage:
    python gen_manifest_entry.py --name doc-review --shelf standalone \\
        --description "Three-pass documentation review: cold read, grounding, voice scan." \\
        --meta-repo J:\\Claude \\
        --file standalone/skills/doc-review/SKILL.md=.claude/skills/doc-review/SKILL.md \\
        --file standalone/skills/doc-review/LICENSE=.claude/skills/doc-review/LICENSE \\
        --file standalone/skills/doc-review/README.md=

A `--file EXPORT_PATH=SOURCE_PATH` pair records a real blob hash from the
source repo's committed HEAD (never the working tree, which may have
uncommitted changes the export shouldn't claim to reflect). A `--file
EXPORT_PATH=` (empty source) marks an export-only file — something that
exists only in the exported copy (a README written for adopters, say) and
carries source_blob/source_hash_type/source_path all null, exactly like the
existing ai-check/humanize entries' own README rows.

Prints the JSON component object to stdout. Paste it into manifest.json's
`components` array by hand, or redirect to a file and merge programmatically
- this script only computes the hard-to-get-right part (real hashes), it does
not touch manifest.json itself.
"""
import argparse
import json
import subprocess
import sys


def blob_hash(meta_repo: str, source_path: str) -> str:
    result = subprocess.run(
        ["git", "-C", meta_repo, "rev-parse", f"HEAD:{source_path}"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise SystemExit(
            f"git rev-parse failed for HEAD:{source_path} in {meta_repo}\n"
            f"{result.stderr.strip()}"
        )
    return result.stdout.strip()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--name", required=True)
    parser.add_argument("--shelf", required=True, choices=["standalone", "process"])
    parser.add_argument("--description", required=True)
    parser.add_argument("--meta-repo", required=True, help="Path to the source repo (e.g. J:\\Claude)")
    parser.add_argument(
        "--file",
        action="append",
        required=True,
        dest="files",
        metavar="EXPORT_PATH=SOURCE_PATH",
        help="Repeatable. SOURCE_PATH empty marks an export-only file (no source_blob).",
    )
    args = parser.parse_args()

    files = []
    for spec in args.files:
        if "=" not in spec:
            raise SystemExit(f"--file must be EXPORT_PATH=SOURCE_PATH (got: {spec!r})")
        export_path, source_path = spec.split("=", 1)
        if source_path:
            files.append(
                {
                    "path": export_path,
                    "source_blob": blob_hash(args.meta_repo, source_path),
                    "source_hash_type": "git-blob",
                    "source_path": source_path,
                }
            )
        else:
            files.append(
                {
                    "path": export_path,
                    "source_blob": None,
                    "source_hash_type": None,
                    "source_path": None,
                }
            )

    component = {
        "name": args.name,
        "shelf": args.shelf,
        "description": args.description,
        "files": files,
    }
    print(json.dumps(component, indent=2))


if __name__ == "__main__":
    main()
